# Generated by Django 4.2.6 on 2023-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awstranscriptions",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "STARTED"),
                    ("IN_PROGRESS", "IN_PROGRESS"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="STARTED",
                max_length=255,
            ),
        ),
    ]
